import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-gray-800 p-4">
          <div className="container mx-auto flex justify-between items-center">
            <div className="flex space-x-4">
              <Link href="/" className="text-white hover:text-gray-300">
                Home
              </Link>
              <Link href="/cars" className="text-white hover:text-gray-300">
                Cars
              </Link>
              <Link href="/trucks" className="text-white hover:text-gray-300">
                Trucks
              </Link>
              <Link href="/lego" className="text-white hover:text-gray-300">
                Lego
              </Link>
              <Link href="/wiese" className="text-white hover:text-gray-300">
                Wiese
              </Link>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
